### ISSUE TITLE
How to remotely deploy code to the BeagleBone?

### ISSUE THREAD

**Issue by bennyn** [jadonk/bonescript#148]
Hello, I am new to the BeagleBone community and I would like to know if it is possible to deploy JavaScript code remotely to the BeagleBone?

Until now I always coded on the BeagleBone (using the Cloud9 environment) itself. But I would like to code on my personal computer and then deploy it from there to the BeagleBone. Is this possible?

I know that the [Tessel](https://tessel.io/) microcontroller supports this way of coding by running `tessel run my-app.js`.

**Comment by jgtaylor** [comment]
i do my dev on my laptop and push to github, then pull from the BBblack.

You could also do a rsync or an scp from your dev host to your BBblack. If you install something like pm2 and use it to watch wherever you're putting your project, it will restart the app if it detects changes, so that after each update iteration, it automatically runs the app.

another possibility (but is kind of overkill) is to run a git server on the BBblack and just push your code there.

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#49
