### ISSUE TITLE
bonescript development

### ISSUE THREAD

**Issue by smuellerus** [jadonk/bonescript#96]
Hi,

I just bought a BeagleBone black and am trying to get up to speed with bonescript. It looks excellent to me and helps me getting started as I already know JavaScript and Node.js. However, I noticed that there are still some bugs and unfinished features. It would be really sad to see this project die. It would be a big loss for BeagleBone, which is suited a lot better than Raspberry Pi for many projects.

Anyways - I really hope development continues. If you guys need cash, I am willing to contribute, or just set up a Kickstarter project.

Best,

Steffen

**Comment by jadonk** [comment]
I'd still love to pull in fixes from octalbonescript and make this one project, but the coordination of the development into sane patches where I understand and agree with the individual changes hasn't happened. Some feature/architecture changes in octalbonescript aren't ones I can support across my current array of users.

**Comment by adityapatadia** [comment]
We have forked bonescript for a very simple reason. The development cycle for bonescript does not suit needs of system developers. It's been exactly one year since last version was pushed to NPM which is 0.2.4. There are several bugs in that version which has not been fixed till date. On the other hand, we continuously fix bugs and release new updates as and when we or our users encounter problems. The average time of closing pull requests is not more than 3 days. 

We also accept that many structural changes were made in bonescript but the reasons were purely to make it more stable. Except 2 changes which are properly documented, we have not made any changes in APIs of core bonescript so users can easily migrate.

As a result of our efforts the users have embraced octalbonescript and the improvements that we made. To compare statistics, the bonescript was downloaded 405 times in last month vis-a-vis octalbonescript was downloaded 648 times in last month as per npmjs.org.

We have a simple goal in mind. We want to make octalbonescript more stable and feature rich in a way that any person knowing Javascript should be able to leverage full power of BeagleBone. Hope the community as a whole will help us achieve that.

Thanks.

**Comment by deepakkarki** [comment]
>As a result of our efforts the users have embraced octalbonescript and the improvements that we made. To compare statistics, the bonescript was downloaded 405 times in last month vis-a-vis octalbonescript was downloaded 648 times in last month as per npmjs.org.

Probably because bonescript ships with the BBB, so no one really has to download it.
That said, octalbonescript looks like a neat project, you and jason should work together to make it one solid project.

**Comment by adityapatadia** [comment]
I wanted to say that number download of OBS are very solid and the project is being embraced well by users. I have tried to merge the project but the efforts did not succeed.

I am going to launch OBS v1.0.0 soon that will have lot of bug fixes and enhancements. Instead of banking on old unmaintained project, community should switch to a library which is maintained rigourously. A lot of community members also complain when I say it is a "better" library. By looking at the codebase of both project, any programmer can realise that OBS code is more readable, follows convention, avoids CPU intensive functions and follows DRY principles. 

In the end, I care for users of the library and anyone who used OBS before, will realise that it "just works". Upcoming v1.0.0 is an effort towards making it more usable and bringing it at par with convention followed by nodejs community. Hope the users will appreciate the hard work done to make their life easier.

**Comment by adityapatadia** [comment]
@deepakkarki It would be great if you can point me to work done by you to improve PRU interface of BeagleBone. It would be great if you can help bring PRU support to OBS by providing some kind of JavaScript package.

**Comment by sputnik63** [comment]
If I can write my opinion, you both (bonescript on octalbonescript) should make your projects "general purpose". I try to explain. Just changing the files bone.js (the configuration) and hw_oldkernel.js (the hardware management) I got a my own version of bonescript that allows to me to manage some linux based boards I'm using (neither BB nor Raspberry). And it seems to work :dart: 
I think that to have a "general purpose" xxxscript that allows people to manage a general linux based litle board could be really a great thing. :smile:

**Comment by jadonk** [comment]
@sputnik63 if you can get the contributors, I'm happy for it to run on lots of other platforms. I just don't have the bandwidth myself.

**Comment by sputnik63** [comment]
As I wrote I already have a my own working version working and integrated into a my local version of [XI](https://github.com/MrYsLab/xi) to interact with Scratch.
I'm a newbie about javascript. By the way, I'm continuing to test and my next goal is to purge all what I don't need for my boards. My only changed files are bone.js and hw_oldkernel.js  file and it works like a charm.

**Comment by adityapatadia** [comment]
@sputnik63 Sounds good. Can you create PR for your changed file? I am ready to make OBS general purpose if it is easy as per your experience. I have a very good experience and ready to devote time to improve OBS.

**Comment by sputnik63** [comment]
@adityapatadia sure I can. I'm working to purge all what I don't need (mainly in bone.js) and I'm trying to do the same "porting" with OBS. Also with my few javascript knowledge I could give my contribution to both projects. I'll give you both my work asap to you and to @jadonk . I already tested it on real hardware.

**Comment by adityapatadia** [comment]
Sounds good. I appreciate your efforts and of course you should suggest the same changes to bonescript.

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#51
